version: "3"
services:
  email2db:
    image: "mmhk/email2db:latest"
    restart: always
    environment:
      - S3_KEY=${S3_KEY}
      - S3_SECRET=${S3_SECRET}
      - S3_REGION=ap-southeast-1
      - S3_BUCKET=s3.test.mixmedia.com
      - S3_PREFIX=email2db
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=email2db
      - MYSQL_USERNAME=${MYSQL_USERNAME}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - TZ=Asia/Hong_Kong
      - HTTP_LIST=0.0.0.0:8843
      - WEB_ROOT=/app/web
      - ZOHO_POP3_HOST=${ZOHO_POP3_HOST}
      - PARSER_TYPE=${PARSER_TYPE}
      - ZOHO_POP3_PORT=995
      - ZOHO_EMAIL=${ZOHO_EMAIL}
      - ZOHO_APP_SECRET=${ZOHO_APP_SECRET}
      - ZOHO_POP3_TLS=true
      - LOG_LEVEL=DEBUG
      - CHECK_INTERVAL=1800
      - FETCH_LIMIT=100
    ports:
      - "8843:8843"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
